version: "3.3"
services:
  gateway:
    container_name: gateway
    image: tomcat:10-jdk16
    ports:
     - 80:8080
    networks:
      - frontend
  backend-for-frontend:
    image: tomcat:10-jdk16
    networks:
      - frontend
      - backend
  backend:
    image: tomcat:10-jdk16
    networks:
      - backend
      - backend-database
  database:
    container_name: database
    image: tomcat:10-jdk16
    networks:
      - backend-database
networks:
  frontend:
  backend:
  backend-database: