version: "3.3"
services:
  gateway:
    container_name: gateway
    image: nginx/unit:1.23.0-go1.15
    ports:
     - 80
    networks:
      - frontend
  backend-for-frontend:
    container_name: backend-for-frontend
    image: tomcat:10-jdk16
    ports:
     - 8080
    networks:
      - frontend
      - backend
  backend:
    container_name: backend
    image: tomcat:10-jdk16
    ports:
     - 8080
    networks:
      - backend
  database:
    container_name: database
    image: tomcat:10-jdk16
    ports:
     - 8080
    networks:
      - backend
networks:
  frontend:
  backend: